apiVersion: v2
name: wso2-amp-observability-extension
description: A Helm chart to add Tracing functionality for the Agent Management Platform, by Deploying and Configuring the Agent Manager Observer.
type: application
version: v1.0.0-rc3
appVersion: "v1.0.0-rc3"

keywords:
  - wso2
  - ai
  - agent-management
  - ai-agents
  - observability

maintainers:
  - name: WSO2
    url: https://wso2.com
